import React, { useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Image from 'next/image';
import Info from '@/components/Info/Info';


const borderRed = {
  borderBottom: 'solid red 3px'
}
const Restaurant = ({data}) => {
  const [tabIndex, setTabIndex] = useState(1);

  const handleAppercuIndex = (e) => {
    e.preventDefault();
    setTabIndex(1);
  }
  const handleMenuIndex = (e) => {
    e.preventDefault();
    setTabIndex(2);
  }
  
  return (
    <div>
      <Head>
        <title>Yes !</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.landing}>
        <Image 
          src={data?.images[0].url}
          alt='room'
          width={1140}
          height={641}
          className={styles.image}
        />
        <div className={styles.showmoreimg}><Info content={`Voir les ${data?.images.length} photos`} variant='danger'/></div>
        <div className={styles['m-container']}>
          <nav className={styles.nav}>
            <a className={styles.navitem} onClick={handleAppercuIndex} style={tabIndex == 1 ? borderRed : {}}>Apperçu</a>
            <a className={styles.navitem} onClick={handleMenuIndex} style={tabIndex == 2 ? borderRed : {}}>Menu</a>
            <div className={styles.trait}></div>
          </nav>
          
          {
            tabIndex == 1 ? 
            <div className={styles.tab}>
              <h1>🤤 Hello, je suis la page d'apperçu ! 😋</h1>
            </div>
            :
            <div className={styles.tab}>
              <h1>🥗 Hello, je suis le menu ! 🍖</h1>
            </div>
          }
        </div>
      </div>


    </div>
  )
}

export default Restaurant;


export const getServerSideProps = async (ctx) => {
  const slug = ctx.query.id;
  const route = `http://localhost:3000/api/restaurant/${slug}`;
  const response = await fetch(route);
  if(response.status == 500){
     return {
      notFound: true, // This will trigger a 404 error page
    };
  }
  const data  = await response.json();
  
  return {
      props: {
        data
      }
  }
}