import React from 'react';
import Head from 'next/head'
import Card from '@/components/Card/Card';
import styles from '@/styles/Home.module.css';
import { v4 as uuidv4 } from 'uuid';

export default function Home({data}) {
  const cards = data?.restaurants.map(item => {
    return {
      name: item?.name,
      img: item?.images[0]?.url,
      categories: [{content: 'Café', variant: 'danger'}, {content: 'Bistrot', variant: 'danger'}, {content: 'Thaï', variant: 'danger'}],
      location: item?.location?.name,
      price: item?.average_price,
      close: 'Fermé',
      id: item.id
    }
  })
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Yes !</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.title}>
        <h2>Restaurants Populaire dans Yaoundé</h2>
        <h3>Voir Plus</h3>
      </div>

      <div className={styles.main}>
          {cards.map(card => (
            <div className={styles.item} key={uuidv4()}>
              <Card 
                id={card.id}
                name={card.name}
                img={card.img}
                categories={card.categories}
                location={card.location}
                price={card.price}
                close={card.close}
              />
            </div>
          ))}
      </div>
    </div>
  )
}

export const getServerSideProps = async () => {
  const response = await fetch("http://localhost:3000/api/restaurant");
  const data  = await response.json();

  return {
      props: {
        data
      }
  }
}
